# Cloud Build configuration for deploying to Cloud Run
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/carelens-360:$SHORT_SHA', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/carelens-360:$SHORT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'carelens-360'
      - '--image'
      - 'gcr.io/$PROJECT_ID/carelens-360:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},GEMINI_API_KEY=${_GEMINI_API_KEY},FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION}'

images:
  - 'gcr.io/$PROJECT_ID/carelens-360:$SHORT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GCS_BUCKET_NAME: 'your-bucket-name'
  _FIRESTORE_COLLECTION: 'clinical_summaries'

